// Dashboard action types
export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const DASHBOARD_RESET = 'DASHBOARD_RESET';

// Statistics Data
export const STATISTICS_REQUEST = 'STATISTICS_REQUEST';
export const STATISTICS_SUCCESS = 'STATISTICS_SUCCESS';
export const STATISTICS_ERROR = 'STATISTICS_ERROR';
export const STATISTICS_RESET = 'STATISTICS_RESET';

// NFT history action types
export const NFT_HISTORY_REQUEST = 'NFT_HISTORY_REQUEST';
export const NFT_HISTORY_SUCCESS = 'NFT_HISTORY_SUCCESS';
export const NFT_HISTORY_ERROR = 'NFT_HISTORY_ERROR';
export const NFT_HISTORY_RESET = 'NFT_HISTORY_RESET';

// Listing of trees action types
export const FETCH_TREES_REQUEST = 'FETCH_TREES_REQUEST';
export const FETCH_TREES_SUCCESS = 'FETCH_TREES_SUCCESS';
export const FETCH_TREES_FAILURE = 'FETCH_TREES_FAILURE';

// Dropdown action types - for IUCN status
export const IUCN_STATUS_REQUEST = 'IUCN_STATUS_REQUEST';
export const IUCN_STATUS_SUCCESS = 'IUCN_STATUS_SUCCESS';
export const IUCN_STATUS_ERROR = 'IUCN_STATUS_ERROR';
export const SET_SELECTED_IUCN_STATUS = 'SET_SELECTED_IUCN_STATUS';
export const IUCN_STATUS_RESET = 'IUCN_STATUS_RESET';

// Dropdown action types - for Organization status
export const ORGANIZATION_REQUEST = 'ORGANIZATION_REQUEST';
export const ORGANIZATION_SUCCESS = 'ORGANIZATION_SUCCESS';
export const ORGANIZATION_ERROR = 'ORGANIZATION_ERROR';
export const SET_SELECTED_ORGANIZATION = 'SET_SELECTED_ORGANIZATION';
export const ORGANIZATION_RESET = 'ORGANIZATION_RESET';

// Dropdown action types - for Sponsor status
export const SPONSOR_REQUEST = 'SPONSOR_REQUEST';
export const SPONSOR_SUCCESS = 'SPONSOR_SUCCESS';
export const SPONSOR_ERROR = 'SPONSOR_ERROR';
export const SET_SELECTED_SPONSOR = 'SET_SELECTED_SPONSOR';
export const SPONSOR_RESET = 'SPONSOR_RESET';

// Dropdown action types - for Country status
export const COUNTRY_REQUEST = 'COUNTRY_REQUEST';
export const COUNTRY_SUCCESS = 'COUNTRY_SUCCESS';
export const COUNTRY_ERROR = 'COUNTRY_ERROR';
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const COUNTRY_RESET = 'COUNTRY_RESET';

// Dropdown action types - for User List
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const USER_RESET = 'USER_RESET';

// Particular Organization Details
export const COUNTRY_LISTING_ORG_ID_REQUEST = 'COUNTRY_LISTING_ORG_ID_REQUEST';
export const COUNTRY_LISTING_ORG_ID_SUCCESS = 'COUNTRY_LISTING_ORG_ID_SUCCESS';
export const COUNTRY_LISTING_ORG_ID_ERROR = 'COUNTRY_LISTING_ORG_ID_ERROR';

//Particular Species Details by User Id
export const SPECIES_LISTING_USER_ID_REQUEST =
  'SPECIES_LISTING_USER_ID_REQUEST';
export const SPECIES_LISTING_USER_ID_SUCCESS =
  'SPECIES_LISTING_USER_ID_SUCCESS';
export const SPECIES_LISTING_USER_ID_ERROR = 'SPECIES_LISTING_USER_ID_ERROR';

// Dropdown action types - for Species status
export const SPECIES_REQUEST = 'SPECIES_REQUEST';
export const SPECIES_SUCCESS = 'SPECIES_SUCCESS';
export const SPECIES_ERROR = 'SPECIES_ERROR';
export const SET_SELECTED_SPECIES = 'SET_SELECTED_SPECIES';
export const SPECIES_RESET = 'SPECIES_RESET';

// Add Species action types
export const ADD_SPECIES_REQUEST = 'ADD_SPECIES_REQUEST';
export const ADD_SPECIES_SUCCESS = 'ADD_SPECIES_SUCCESS';
export const ADD_SPECIES_FAILURE = 'ADD_SPECIES_FAILURE';
export const RESET_SPECIES_STATE = 'RESET_SPECIES_STATE';

// Add User action types
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const RESET_USER_STATE = 'RESET_USER_STATE';

// Add Organisation action types
export const ADD_ORG_REQUEST = 'ADD_ORG_REQUEST';
export const ADD_ORG_SUCCESS = 'ADD_ORG_SUCCESS';
export const ADD_ORG_FAILURE = 'ADD_ORG_FAILURE';
export const RESET_ORG_STATE = 'RESET_ORG_STATE';

// Update Organisation action types
export const UPDATE_ORG_REQUEST = 'UPDATE_ORG_REQUEST';
export const UPDATE_ORG_SUCCESS = 'UPDATE_ORG_SUCCESS';
export const UPDATE_ORG_FAILURE = 'UPDATE_ORG_FAILURE';
export const RESET_UPDATE_ORG_STATE = 'RESET_UPDATE_ORG_STATE';

// Particular Organization Details
export const ORGANIZATION_DETAILS_REQUEST = 'ORGANIZATION_DETAILS_REQUEST';
export const ORGANIZATION_DETAILS_SUCCESS = 'ORGANIZATION_DETAILS_SUCCESS';
export const ORGANIZATION_DETAILS_ERROR = 'ORGANIZATION_DETAILS_ERROR';

// Tree Review Action Types
export const APPROVE_TREE_REQUEST = 'APPROVE_TREE_REQUEST';
export const APPROVE_TREE_SUCCESS = 'APPROVE_TREE_SUCCESS';
export const APPROVE_TREE_FAILURE = 'APPROVE_TREE_FAILURE';

export const REJECT_TREE_REQUEST = 'REJECT_TREE_REQUEST';
export const REJECT_TREE_SUCCESS = 'REJECT_TREE_SUCCESS';
export const REJECT_TREE_FAILURE = 'REJECT_TREE_FAILURE';

// Reset action type to clear state after navigation
export const RESET_TREE_REVIEW_STATE = 'RESET_TREE_REVIEW_STATE';

// Species Assignment Action Types
export const ASSIGN_SPECIES_REQUEST = 'ASSIGN_SPECIES_REQUEST';
export const ASSIGN_SPECIES_SUCCESS = 'ASSIGN_SPECIES_SUCCESS';
export const ASSIGN_SPECIES_FAILURE = 'ASSIGN_SPECIES_FAILURE';
export const RESET_SPECIES_ASSIGNMENT_STATE = 'RESET_SPECIES_ASSIGNMENT_STATE';

// NFT Assignment Action Types
export const ASSIGN_NFT_REQUEST = 'ASSIGN_NFT_REQUEST';
export const ASSIGN_NFT_SUCCESS = 'ASSIGN_NFT_SUCCESS';
export const ASSIGN_NFT_FAILURE = 'ASSIGN_NFT_FAILURE';
export const RESET_NFT_ASSIGNMENT_STATE = 'RESET_NFT_ASSIGNMENT_STATE';

// Search-related action types
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

// Delete Species Action types
export const DELETE_SPECIES_REQUEST = 'DELETE_SPECIES_REQUEST';
export const DELETE_SPECIES_SUCCESS = 'DELETE_SPECIES_SUCCESS';
export const DELETE_SPECIES_FAILURE = 'DELETE_SPECIES_FAILURE';
export const RESET_DELETE_SPECIES = 'RESET_DELETE_SPECIES';

// Add Sponsor Action types
export const ADD_SPONSOR_REQUEST = 'ADD_SPONSOR_REQUEST';
export const ADD_SPONSOR_SUCCESS = 'ADD_SPONSOR_SUCCESS';
export const ADD_SPONSOR_FAILURE = 'ADD_SPONSOR_FAILURE';
export const RESET_SPONSOR_STATE = 'RESET_SPONSOR_STATE';

// Particular Sponsor Details
export const SPONSOR_DETAILS_REQUEST = 'SPONSOR_DETAILS_REQUEST';
export const SPONSOR_DETAILS_SUCCESS = 'SPONSOR_DETAILS_SUCCESS';
export const SPONSOR_DETAILS_ERROR = 'SPONSOR_DETAILS_ERROR';

// Delete Org Species Action types
export const DELETE_ORG_SPECIES_REQUEST = 'DELETE_ORG_SPECIES_REQUEST';
export const DELETE_ORG_SPECIES_SUCCESS = 'DELETE_ORG_SPECIES_SUCCESS';
export const DELETE_ORG_SPECIES_FAILURE = 'DELETE_ORG_SPECIES_FAILURE';
export const RESET_ORG_DELETE_SPECIES = 'RESET_ORG_DELETE_SPECIES';

// Mint Nft Action types
export const MINT_NFT_REQUEST = 'MINT_NFT_REQUEST';
export const MINT_NFT_SUCCESS = 'MINT_NFT_SUCCESS';
export const MINT_NFT_FAILURE = 'MINT_NFT_FAILURE';
export const RESET_MINT_NFT = 'RESET_MINT_NFT';

// Edit Sponsor Action types
export const UPDATE_SPONSOR_REQUEST = 'UPDATE_SPONSOR_REQUEST';
export const UPDATE_SPONSOR_SUCCESS = 'UPDATE_SPONSOR_SUCCESS';
export const UPDATE_SPONSOR_FAILURE = 'UPDATE_SPONSOR_FAILURE';
export const RESET_SPONSOR_UPDATE_STATE = 'RESET_SPONSOR_UPDATE_STATE';

// Password reset constants
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const RESET_PASSWORD_CLEAR = 'RESET_PASSWORD_CLEAR';

// Password reset submission constants
export const RESET_PASSWORD_SUBMIT_REQUEST = 'RESET_PASSWORD_SUBMIT_REQUEST';
export const RESET_PASSWORD_SUBMIT_SUCCESS = 'RESET_PASSWORD_SUBMIT_SUCCESS';
export const RESET_PASSWORD_SUBMIT_ERROR = 'RESET_PASSWORD_SUBMIT_ERROR';
export const RESET_PASSWORD_SUBMIT_CLEAR = 'RESET_PASSWORD_SUBMIT_CLEAR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const RESET_LOGOUT = 'RESET_LOGOUT';

export const SIGNUP_LINK_REQUEST = 'SIGNUP_LINK_REQUEST';
export const SIGNUP_LINK_SUCCESS = 'SIGNUP_LINK_SUCCESS';
export const SIGNUP_LINK_ERROR = 'SIGNUP_LINK_ERROR';
export const SIGNUP_LINK_RESET = 'SIGNUP_LINK_RESET';

export const USER_RESET_LINK_REQUEST = 'USER_RESET_LINK_REQUEST';
export const USER_RESET_LINK_SUCCESS = 'USER_RESET_LINK_SUCCESS';
export const USER_RESET_LINK_ERROR = 'USER_RESET_LINK_ERROR';
export const USER_RESET_LINK_RESET = 'USER_RESET_LINK_RESET';
